version: 1.0.{build}
image: Visual Studio 2022

configuration: Release
platform: x64

before_build:
  - echo "LMWallpaper Build Starting"
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if exist build rmdir /s /q build
  - if exist CMakeCache.txt del CMakeCache.txt

build_script:
  - echo "CMake Configure"
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 17 2022" -A x64 ..
  - echo "Building Project"
  - cmake --build . --config Release
  - echo "Build Results"
  - dir Release\*.exe

after_build:
  - echo "Preparing Artifacts"
  - cd ..
  - mkdir artifact
  - xcopy build\Release\*.exe artifact\ /Y
  - dir artifact\

artifacts:
  - path: artifact\
    name: LMWallpaper-Windows-x64
    type: zip

on_failure:
  - echo "Build Failed - Debug Info"
  - cmake --version
  - if exist build dir build /s

on_success:
  - echo "Build Successful!"