image: Visual Studio 2022

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

configuration: Release
platform: x64

before_build:
  - cmd: call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - cmake -S . -B build -A x64 -DCMAKE_BUILD_TYPE=Release
  - cmake --build build --config Release

artifacts:
  - path: build\Release\
    name: LMWallpaper-x64-Build
